export const INITIAL_STATE = 'INITIAL_STATE';

// user reducer
export const SET_USER_LIST_USER_REDUCER = 'SET_USER_LIST_USER_REDUCER';
export const SET_SELECTED_USER_USER_REDUCER = 'SET_SELECTED_USER_USER_REDUCER';
export const SET_FETCHING_USERS_USER_REDUCER =
  'SET_FETCHING_USERS_USER_REDUCER';
